#!/bin/bash

export GUM_FORMAT_THEME="dracula"
export GUM_SPIN_SPINNER="dot"
export GUM_SPIN_SPINNER_FOREGROUND="1500"
export GUM_CONFIRM_UNSELECTED_FOREGROUND="1500"
export GUM_CONFIRM_SELECTED_FOREGROUND="1500"
export GUM_CONFIRM_SELECTED_BACKGROUND="1500"
export GUM_CHOOSE_CURSOR_FOREGROUND="1500"
export GUM_CHOOSE_SELECTED_FOREGROUND="1500"
export FOREGROUND="1500"
export BORDER_FOREGROUND="1500"